modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "fwaystones"
version = "${version}"
displayName = "Forge Waystones"
authors = "LordDeatHunter"
description = "A better way of transport!"
logoFile = "icon.png"

[[dependencies.fwaystones]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "cloth_config"
mandatory = true
versionRange = "[8,)"
ordering = "AFTER"
side = "BOTH"

