modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL="https://github.com/LordDeatHunter/FabricWaystones/issues"
license = "MIT License"

[[mods]]
modId = "fwaystones"
version = "${version}"
displayName = "Forge Waystones"
authors = "LordDeatHunter"
description = "A better way of transport!"
logoFile = "icon.png"

[[dependencies.fwaystones]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fwaystones]]
modId = "cloth_config"
mandatory = true
versionRange = "[10.0.96,)"
ordering = "AFTER"
side = "BOTH"