plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version + "+mc" + project.minecraft_version
group = project.maven_group

base {
    archivesName = project.archives_base_name;
}

repositories {
    maven { url = "https://www.cursemaven.com" }
    maven {
        name = "JourneyMap (Public)"
        url = "https://jm.gserv.me/repository/maven-public/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { url 'https://maven.wispforest.io' }
    maven { url 'https://jitpack.io' }
    maven {
        url "https://nexus.resourcefulbees.com/repository/telepathicgrunt/"
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:22.0.0'

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    compileOnly("com.telepathicgrunt:RepurposedStructures:${project.repurposed_structures_version}-fabric") { transitive = false }
    api("info.journeymap:journeymap-api-fabric:$project.journeymap_api_version") { transitive = false }
    implementation("maven.modrinth:lithostitched:1.7.13-fabric-26.1") { transitive = false }

    annotationProcessor implementation("io.wispforest:owo-lib:${project.owo_version}")
    include "io.wispforest:owo-sentinel:${project.owo_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/fwaystones.accesswidener")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
    }
}
