plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version + "+mc" + project.minecraft_version
group = project.maven_group

base {
    archivesName = project.archives_base_name;
}

repositories {
    maven { url = "https://www.cursemaven.com" }
    maven {
        name = "JourneyMap (Public)"
        url = "https://jm.gserv.me/repository/maven-public/"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { url 'https://maven.wispforest.io' }
    maven { url 'https://jitpack.io' }
    maven {
        url "https://nexus.resourcefulbees.com/repository/telepathicgrunt/"
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:22.0.0'

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modCompileOnly "com.telepathicgrunt:RepurposedStructures:${project.repurposed_structures_version}-fabric"
    modApi "info.journeymap:journeymap-api-fabric:$project.journeymap_api_version"
    modImplementation "maven.modrinth:lithostitched:1.7.2-fabric-21.11"

    annotationProcessor modImplementation("io.wispforest:owo-lib:${project.owo_version}")
    include "io.wispforest:owo-sentinel:${project.owo_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/fwaystones.accesswidener")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
    }
}
