name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: bug
assignees: 'LordDeatHunter'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: stepsToReproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. Please also include a list of other mods/modpacks installed.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: expectedBehaviour
    attributes:
      label: Expected behavior
      description: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: modVersion
    attributes:
      label: Mod Version
      description: "Please select the used version of 'Fabric Waystones'."
      options:
        - "v3.1.1 or newer"
        - "v3.1.0"
        - "v3.0.8"
        - "v3.0.7 or newer"
        - "v3.0.6"
        - "v3.0.5"
        - "v3.0.4"
        - "v3.0.3"
        - "v3.0.2"
        - "v3.0.1"
        - "v3.0.0"
        - "v2.6.0-CONVERT"
        - "v2.5.0"
        - "v2.4.1"
        - "v2.4.0"
        - "v2.3.5"
        - "v2.3.4"
        - "v2.3.3"
        - "v2.3.2"
        - "v2.3.1"
        - "v2.3.0-beta"
        - "v2.2.3"
        - "v2.2.2"
        - "v2.2.1"
        - "v2.2.0"
        - "v2.1.3"
        - "v2.1.2"
        - "v2.1.1"
        - "v2.1.0"
        - "v2.0.4"
        - "v2.0.4-beta"
        - "v2.0.3"
        - "v2.0.2"
        - "v2.0.1"
        - "v2.0.0"
    validations:
      required: true
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: "Please select the used version of 'Minecraft'."
      options:
        - "1.20 or newer"
        - "1.19.4"
        - "1.19.3"
        - "1.19.2"
        - "1.19.1"
        - "1.19"
        - "1.18.2"
        - "1.18.1"
        - "1.18"
        - "1.18-snapshot"
        - "1.17.1"
        - "1.16.5"
        - "Other"
    validations:
      required: true
  - type: dropdown
    id: javaVersion
    attributes:
      label: Java Version
      description: "Please select the used version of 'Java'."
      options:
        - "Java 18+"
        - "Java 17"
        - "Java 16"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: fabricVersion
    attributes:
      label: Fabric Version
      description: "Please enter the used version of 'Fabric' and 'Fabric API'."
      value: |
        - **Fabric:** ex. 0.12.5-1-17-1
        - **Fabric API:** ex. 0.42.1+1.17
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anythingElse
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
